### PR TITLE
Add command timeout

### PR DESCRIPTION
**Pull request by allen-servedio**
This adds the ability to set a timeout for commands by default (right now it is 60 seconds).

### CODE REVIEW

**Comment by lerouxrgd** [comment]
Thank you !

**Comment by allen-servedio** [comment]
Thanks for the quick merge @lerouxrgd ! Do you know when you will be releasing the feature?

**Comment by lerouxrgd** [comment]
I will make a proper release later today !

**Review by shveik — COMMENTED** [review]
@lerouxrgd thanks for taking this PR, there is an issue when upgrading lettuce, one of the tests is now returning an error instead of nil. we were hoping that you could release this so that we can start testing in our env. thanks!

**Comment by lerouxrgd** [comment]
Got it, I will run the usual tests beforehand.

**Comment by lerouxrgd** [comment]
@shveik Actullay I run the test without errors:
```
Ran 50 tests containing 719 assertions.
```
Do you have precisions about the errors you had ? Or your Redis version ?

There are warnings for reflection though (I will investigate them).

**Comment by shveik** [comment]
this is what i got: 
`➜  celtuce-twc git:(master) ✗ lein test
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.

lein test celtuce.cluster-dynamic-test

lein test celtuce.cluster-manifold-test

lein test :only celtuce.cluster-manifold-test/scripting-commands-test

FAIL in (scripting-commands-test) (cluster_manifold_test.clj:318)
simple scripting
expected: (thrown? io.lettuce.core.RedisCommandExecutionException (clojure.core/deref (redis/evalsha *cmds* sha :integer [])))
  actual: nil
Apr 14, 2021 4:09:56 PM io.lettuce.core.RedisChannelHandler closeAsync
WARNING: Connection is already closed

lein test celtuce.cluster-sync-test

lein test celtuce.connector-test

lein test celtuce.pool-test

lein test celtuce.server-dynamic-test

lein test celtuce.server-manifold-test

lein test celtuce.server-sync-test

Ran 50 tests containing 719 assertions.
1 failures, 0 errors.
Tests failed.`

**Comment by lerouxrgd** [comment]
I have 

```
$ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)
```
And Redis `6.2.1` on Manjaro and everything is fine (I have fixed the reflection warnings on master).

Do you run the tests like this ?
```
(cd modules/celtuce-core/; lein do clean, install)
(cd modules/celtuce-pool/; lein do clean, install)
(cd modules/celtuce-manifold/; lein do clean, install)

lein test
```

**Comment by shveik** [comment]
same result. 

my java is different. Redis is same, 6.2.1, on Big Sur

➜  celtuce-twc git:(master) ✗ java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+36-2231)
OpenJDK 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

**Comment by lerouxrgd** [comment]
Can you try with 15 ? Or 11 which is the latest LTS ?

**Comment by shveik** [comment]
Yes, I will do it later tonight. If you want to cut us a release candidate, we can start testing that in parallel

**Comment by shveik** [comment]
Hey @lerouxrgd sorry it took me a bit longer to get to this, here is the output, as you expected, it's only on 16: 

```
➜  ~ jenv local 11
➜  ~ cd src/celtuce-twc
➜  celtuce-twc git:(master) ✗

➜  celtuce-twc git:(master) ✗
➜  celtuce-twc git:(master) ✗ lein test

lein test celtuce.cluster-dynamic-test

lein test celtuce.cluster-manifold-test

lein test celtuce.cluster-sync-test

lein test celtuce.connector-test

lein test celtuce.pool-test

lein test celtuce.server-dynamic-test

lein test celtuce.server-manifold-test

lein test celtuce.server-sync-test

Ran 50 tests containing 719 assertions.
0 failures, 0 errors.
➜  celtuce-twc git:(master) ✗ jenv local 11
➜  celtuce-twc git:(master) ✗ lein test

lein test celtuce.cluster-dynamic-test

lein test celtuce.cluster-manifold-test

lein test celtuce.cluster-sync-test

lein test celtuce.connector-test

lein test celtuce.pool-test

lein test celtuce.server-dynamic-test

lein test celtuce.server-manifold-test

lein test celtuce.server-sync-test

Ran 50 tests containing 719 assertions.
0 failures, 0 errors.
➜  celtuce-twc git:(master) ✗ jenv local 16
➜  celtuce-twc git:(master) ✗ lein test
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.

lein test celtuce.cluster-dynamic-test

lein test celtuce.cluster-manifold-test

lein test :only celtuce.cluster-manifold-test/scripting-commands-test

FAIL in (scripting-commands-test) (cluster_manifold_test.clj:318)
simple scripting
expected: (thrown? io.lettuce.core.RedisCommandExecutionException (clojure.core/deref (redis/evalsha *cmds* sha :integer [])))
  actual: nil
Apr 15, 2021 9:37:53 AM io.lettuce.core.RedisChannelHandler closeAsync
WARNING: Connection is already closed

lein test celtuce.cluster-sync-test

lein test celtuce.connector-test

lein test celtuce.pool-test

lein test celtuce.server-dynamic-test

lein test celtuce.server-manifold-test

lein test celtuce.server-sync-test

Ran 50 tests containing 719 assertions.
1 failures, 0 errors.
Tests failed.
➜  celtuce-twc git:(master) ✗

**Comment by lerouxrgd** [comment]
Ok so it looks like an issue of Lettuce with JDK 16 then, nothing I can do about it I guess.

**Comment by lerouxrgd** [comment]
Actually I have a doubt, @shveik could you try to add a @ at [this line](https://github.com/lerouxrgd/celtuce/blob/master/test/celtuce/cluster_manifold_test.clj#L317)

So `@(redis/script-flush *cmds*)` instead of `(redis/script-flush *cmds*)`.

(Sorry I don't have a JDK 16 setup available easily now)

**Comment by shveik** [comment]
same error as before, @lerouxrgd

**Comment by lerouxrgd** [comment]
Ok ... Thank you for checking though !

**Comment by allen-servedio** [comment]
Java 8 has the same issue:

```
> java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)

> lein test

lein test celtuce.cluster-dynamic-test

lein test celtuce.cluster-manifold-test

lein test :only celtuce.cluster-manifold-test/scripting-commands-test

FAIL in (scripting-commands-test) (cluster_manifold_test.clj:318)
simple scripting
expected: (thrown? io.lettuce.core.RedisCommandExecutionException (clojure.core/deref (redis/evalsha *cmds* sha :integer [])))
  actual: nil

lein test celtuce.cluster-sync-test

lein test celtuce.connector-test

lein test celtuce.pool-test

lein test celtuce.server-dynamic-test

lein test celtuce.server-manifold-test

lein test celtuce.server-sync-test

Ran 50 tests containing 719 assertions.
1 failures, 0 errors.
Tests failed.
```

But, I think I know what is going on... Looking over the release notes, I think this function went async. So to test that, I just added a simple delay into the test - they now pass with no issue:

```
> lein test

lein test celtuce.cluster-dynamic-test

lein test celtuce.cluster-manifold-test

lein test celtuce.cluster-sync-test

lein test celtuce.connector-test

lein test celtuce.pool-test

lein test celtuce.server-dynamic-test

lein test celtuce.server-manifold-test

lein test celtuce.server-sync-test

Ran 50 tests containing 719 assertions.
0 failures, 0 errors.
```

```
(deftest scripting-commands-test
  (let [script "return 10"
        sha    "080c414e64bca1184bc4f6220a19c4d495ac896d"]
    (with-str-cmds
      (testing "simple scripting"
        (is (= 10  @(redis/eval    *cmds* script :integer [])))
        (is (= sha (redis/digest  *cmds* script)))
        (is (= 10  @(redis/evalsha *cmds* sha :integer [])))
        (redis/script-flush *cmds*)
        (Thread/sleep 200)
        (is (thrown? io.lettuce.core.RedisCommandExecutionException
                     @(redis/evalsha *cmds* sha :integer [])))))))
```

When I remove the `(Thread/sleep 200)` the error comes back. I am sure there is a better way to wait for the flush to finish.

**Comment by allen-servedio** [comment]
#25 fixes it for Java 8 at least

**Pull request merged**
